[package]
name = "zfetch"
version = "0.1.0"
edition = "2021"
authors = ["ilker <byilker545@gmail.com>"]
description = "Yet another system information fetcher for Linux"
license = "GPL-3.0"

[dependencies]
sysinfo = "0.30"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

